apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "necesse.fullname" . }}-configmap
  labels:
    {{- include "necesse.labels" . | nindent 4 }}
data: {{ tpl (.Files.Glob "files/*").AsConfig . | nindent 2 }}
