apiVersion: v1
kind: Service
metadata:
  name: {{ include "necesse.fullname" . }}-service
  labels:
    {{- include "necesse.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.cfg.port }}
      protocol: UDP
  selector:
    {{- include "necesse.selectorLabels" . | nindent 4 }}
  type: ClusterIP
