apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-core-keeper-server.fullname" . }}
  annotations:
    "helm.sh/resource-policy": keep
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 20Gi
