kind: Secret
apiVersion: v1
metadata:
  name: {{ include "k8s-core-keeper-server.fullname" . }}
data:
  DATA_PATH: {{ "" | b64enc }}
  DISCORD_HOOK: {{ .Values.discord_hook | b64enc }}
  DISCORD: {{ "1" | b64enc }}
  GAME_ID: {{ "" | b64enc }}
  MAX_PLAYERS: {{ "10" | b64enc }}
  SEASON: {{ "" | b64enc }}
  WORLD_INDEX: {{ "0" | b64enc }}
  WORLD_NAME: {{ "Cillian Murphy The Core" | b64enc }}
  WORLD_SEED: {{ "0" | b64enc }}
type: Opaque
