apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-core-keeper-server.fullname" . }}
  labels:
    {{- include "k8s-core-keeper-server.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: 27015
      nodePort: 30001
      protocol: UDP
      name: gameudp
      targetPort: gameudp
  selector:
    {{- include "k8s-core-keeper-server.selectorLabels" . | nindent 4 }}