apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sleeper
  labels:
    app: sleeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sleeper
  template:
    metadata:
      labels:
        app: sleeper
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          command:
            - /bin/bash
          args:
            - -c
            - sleep infinity
          volumeMounts:
            - name: data
              mountPath: "/data"
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-data